spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/taskmanager?ApplicationName=MyApp
    username: postgres
    password: postgres

  mail:
    port: 587
    host: smtp.gmail.com
    username: e.sikorski1@gmail.com
    password: qlbzmirxssznggdv
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true

server:
  port: 80

jwt:
  secret: NDQ1ZjAzNjQtMzViZi00MDRjLTljZjQtNjNjYWIyZTU5ZDYw
  issuer: ITAcademy